### ISSUE TITLE
Environment question

### ISSUE THREAD

**Issue by Zeitecho** [ZhangGongjie/MapVR#6]
Thank you for your excellent work, but I have an issue with environment configuration. I encountered an error "ModuleNotFoundError: No module named 'native_rasterizer'" while configuring my environment. The error is thrown in the file "projects/mmdet3d_plugin/maptr/losses/diff_ras/polygon.py". I tried to solve this problem on my own but failed. I couldn't find any solutions to this type of environment issue online. Do you have any suggestions?

**Comment by ZhangGongjie** [comment]
try to run the codes below:

cd ./projects/mmdet3d_plugin/maptr/losses/diff_ras/
python setup.py  develop 

Please let me know whether this solves the problem. Thanks!

**Comment by Zeitecho** [comment]
This method can effectively solve the problem. Thank you for your answer.

**Comment by Zeitecho** [comment]
> try to run the codes below:
> 
> cd ./projects/mmdet3d_plugin/maptr/losses/diff_ras/ python setup.py develop
> 
> Please let me know whether this solves the problem. Thanks!

This method can effectively solve the problem. Thank you for your answer.
